// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:hash/domain/models/app_settings.dart';
import 'package:hash/domain/models/call_message.dart';
import 'package:hash/domain/models/call_settings.dart';
import 'package:hash/domain/models/contact.dart';
import 'package:hash/domain/models/message.dart';
import 'package:hash/domain/models/note.dart';
import 'package:hash/domain/models/queued_message.dart';
import 'package:hash/domain/models/queued_receipt.dart';
import 'package:hash/domain/models/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CallMessageAdapter());
    registerAdapter(CallSettingsAdapter());
    registerAdapter(ChecklistItemAdapter());
    registerAdapter(ContactAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MessageStatusAdapter());
    registerAdapter(MessageTypeAdapter());
    registerAdapter(NoteAdapter());
    registerAdapter(NoteTypeAdapter());
    registerAdapter(QueuedMessageAdapter());
    registerAdapter(QueuedReceiptAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CallMessageAdapter());
    registerAdapter(CallSettingsAdapter());
    registerAdapter(ChecklistItemAdapter());
    registerAdapter(ContactAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MessageStatusAdapter());
    registerAdapter(MessageTypeAdapter());
    registerAdapter(NoteAdapter());
    registerAdapter(NoteTypeAdapter());
    registerAdapter(QueuedMessageAdapter());
    registerAdapter(QueuedReceiptAdapter());
    registerAdapter(UserAdapter());
  }
}
